### ISSUE TITLE
好像每次提交任务都会生成两个歌曲

### ISSUE THREAD

**Issue by buzhia** [yihong0618/SunoSongsCreator#11]
我在官网查看任务列表，每次提交任务都会提交两个，但是返回的结果只有一个，这会扣除两次积分。
![image](https://github.com/yihong0618/SunoSongsCreator/assets/125193922/3c123402-abe4-4a6e-b5a3-6f4f3ccd95a9)

**Comment by liuhetian** [comment]
> 先关了哈

生成2个但是似乎只下载了一个，请问可以两个都下载吗

**Comment by yihong0618** [comment]
> > 先关了哈
> 
> 生成2个但是似乎只下载了一个，请问可以两个都下载吗

暂时不行，因为下载太慢了。。。我们觉得不太值得。

**Comment by jeremygan2021** [comment]
我们也希望能够下载两个，要是可以的话
