### ISSUE TITLE
如何使用instrumental 按钮

### ISSUE THREAD

**Issue by ZZHbible** [yihong0618/SunoSongsCreator#14]
当我使用
{
"prompt": "",
"mv": "chirp-v3-0",
"title": "hello world",
"tags": "Pop, folk, easy listening, anime, blues, country, classical"
}'
这样的超参数，但还是会生成带有歌词的歌曲，是要再加什么参数嘛，使用F12看接口的时候，没看到相应的接口参数，希望能得到帮助

**Comment by yihong0618** [comment]
这个我写死的。。
make_instrumental: True 这样就生成无歌词的了，你需要先自己改。

**Comment by yihong0618** [comment]
改完用 clone 的方式
然后 pip install .

**Comment by ZZHbible** [comment]
> 这个我写死的。。 make_instrumental: True 这样就生成无歌词的了，你需要先自己改。

我clone到本地然后改成True了，但是好像还是不太行，就直接本地导包，明天我再测试一下，我按F12，看v2的接口，但是没有看到make_instrumental的参数，emm..

**Comment by yihong0618** [comment]
@ZZHbible 更新了加了一个参数
i.save_songs("大江东去，浪淘尽，千古风流人物。故垒西边，人道是、三国周郎赤壁。乱石穿空，惊涛拍岸，卷起千堆雪。江山如画，一时多少豪杰。遥想公瑾当年，小乔初嫁了，雄姿英发。","output", is_custom=True, title="test", tags="轻松的R&B, BPM60, 小调, 电吉他、贝斯、键盘和轻鼓, 男性歌手", make_instrumental=True)

**Comment by ZZHbible** [comment]
这应该还是不行，如果生成纯音乐的话，prompt应该为空，make_instrumental的参数也没看到传过去..
<img width="1302" alt="image" src="https://github.com/yihong0618/SunoSongsCreator/assets/55887949/8ff73e76-3129-4ffb-8e6f-248eadcb3aed">

**Comment by yihong0618** [comment]
明白了，我再看看，谢谢
