### ISSUE TITLE
Not working, not get auth_token. Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by OlegRuban-ai** [yihong0618/SunoSongsCreator#20]
Since yesterday evening the code stopped working. Doesn't work during authentication token retrieval phase. Falls
![1](https://github.com/yihong0618/SunoSongsCreator/assets/61088564/14b43137-7259-40aa-ba04-617da2a9c2e4)

**Comment by yihong0618** [comment]
get a new cookie and try again

**Comment by OlegRuban-ai** [comment]
> get a new cookie and try again

I replaced the links for the token with these

get_session_url = (
    "https://clerk.suno.com/v1/client/?_clerk_js_version=4.72.0-snapshot.vc141245"
)
exchange_token_url = "https://clerk.suno.com/v1/client/sessions/{sid}/tokens/api?_clerk_js_version=4.72.0-snapshot.vc141245"

I updated the cookies completely and still get the error "Failed to get session id"

**Comment by OlegRuban-ai** [comment]
succeeded with vpn, without it cloudflare blocked access for authentication. Thank you.
