### ISSUE TITLE
What can do to download music without lyrics

### ISSUE THREAD

**Issue by K-Alex13** [yihong0618/SunoSongsCreator#26]
I want to generate music without lyrics, what can I do with this api

**Comment by yihong0618** [comment]
can not for now...
Maybe update this weekend

**Comment by K-Alex13** [comment]
Thank you I can wait, but can you please give me an idea what can I do to achieve this function? Like change the url or change the arguments of the data

**Comment by yihong0618** [comment]
> Thank you I can wait, but can you please give me an idea what can I do to achieve this function? Like change the url or change the arguments of the data

comment these lines https://github.com/yihong0618/SunoSongsCreator/blob/main/suno/suno.py#L270-L276

**Comment by K-Alex13** [comment]
From what I understand that this function is download the lyrics, not generate a song without lyrics

**Comment by yihong0618** [comment]
> From what I understand that this function is download the lyrics, not generate a song without lyrics

I got your idea....it need you reverse the api and found the args.

**Comment by K-Alex13** [comment]
thank you very much
