### ISSUE TITLE
经常报这个错，我已经使用vpn了还是不行 可以麻烦您看看吗

### ISSUE THREAD

**Issue by K-Alex13** [yihong0618/SunoSongsCreator#30]
curl_cffi.requests.errors.RequestsError: Failed to perform, curl: (28) Connection timed out after 30005 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

**Comment by yihong0618** [comment]
好我们看看

**Comment by K-Alex13** [comment]
我换了一台电脑 还是一样的问题

**Comment by K-Alex13** [comment]
在相同环境下，一个月前是可以正常使用的

**Comment by yihong0618** [comment]
有可能需要该代码了，抱歉精力有限，有时间我会去看一下

**Comment by K-Alex13** [comment]
麻烦您了，如果有修改可以告知一下我

**Comment by K-Alex13** [comment]
您能给提个修改方向吗 我去尝试一下 也许也可以？

**Comment by yihong0618** [comment]
我这里没问题

你得重新登陆来拿这个 url 里的 cookie
https://clerk.suno.com/v1/client?_clerk_js_version=4.73.4

**Comment by K-Alex13** [comment]
好哒 我再试试

**Comment by K-Alex13** [comment]
![image](https://github.com/user-attachments/assets/2bafce3d-23e0-40d5-8617-1b8c281ebde2)
还是不太行 我拿的是下面图片的cookie
![image](https://github.com/user-attachments/assets/f1d38257-73a0-4d7d-9659-c5dbf0b00ca7)

**Comment by K-Alex13** [comment]
是要将代码里的地址修改为您新发的吗

**Comment by yihong0618** [comment]
不需要，复制这个 cookie 参考 README 就行我这里没问题。
但现在可能需要全局的梯子
你得确定你的 terminal 能访问 google
curl google.com 能 curl

**Comment by K-Alex13** [comment]
确认了 是我terminal不能curl google的问题
