### ISSUE TITLE
Exception: Failed to get session id

### ISSUE THREAD

**Issue by tuocan** [yihong0618/SunoSongsCreator#4]
Hi, thank you for this project. It was working perfectly for me until last night when I started getting the following error every time I run my program:
```
  File "/home/user/Development/suno-bot/SunoSongsCreator/suno/suno.py", line 46, in __init__
    auth_token = self._get_auth_token()
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/Development/suno-bot/SunoSongsCreator/suno/suno.py", line 56, in _get_auth_token
    raise Exception("Failed to get session id")
Exception: Failed to get session id
```
The error triggers when I try initializing your project with this line: `SongsGen(cookie)`.
I have tested it with multiple accounts which I have confirmed work when using the web version.

If you have any insight on why this might be happening, I would very much appreciate it. Thank you again for this project.

**Comment by yihong0618** [comment]
you need to `export SUNO_COOKIE=xxxx` in every session
or add it to .bashrc please google or chatgpt it how to

**Comment by tuocan** [comment]
Just tried that, still receiving the same error.

I want to clarify that I'm importing your project as a library to use with my own code. I receive this error when I include the line: `SongsGen("xxxxx")`, with the "xxxxx" being my Suno AI cookie

**Comment by yihong0618** [comment]
will check that now, thanks

**Comment by yihong0618** [comment]
@tuocan pip install -U suno_songs 
and try again

**Comment by tuocan** [comment]
It's working now, thank you!

**Comment by tuocan** [comment]
Actually, I thought it was working. Now I'm receiving a new error:
```
..................Token expired, renewing...
{
    'errors': [{'message': 'Session not found', 'long_message': 'No session was found with id None', 'code': 'resource_not_found'}],
    'clerk_trace_id': '73b8659546507f7db39edad263c4db9c'
}
'str' object has no attribute 'get'
```

**Comment by yihong0618** [comment]
> Actually, I thought it was working. Now I'm receiving a new error:
> 
> ```
> ..................Token expired, renewing...
> {
>     'errors': [{'message': 'Session not found', 'long_message': 'No session was found with id None', 'code': 'resource_not_found'}],
>     'clerk_trace_id': '73b8659546507f7db39edad263c4db9c'
> }
> 'str' object has no attribute 'get'
> ```

Just re-run it, this happens occasionally I haven't found a better way to do it yet
